### ISSUE TITLE
Write APIs to get organizations by accountId

### ISSUE THREAD

**Issue by duongdev** [targeek/guru-erp#167]
Expected client-side usage:

Call a React Hook:

```javascript
const orgs = useFindOrgsByAccountIdQuery({ variables: { id: account.id } })
```

Result:

```json5
{
  "orgs": [{
    "id": "...",
    "createdByAccountId": "", // To know if current account is owner
    "name": "",
    "namespace": "",
    "logo": "",
    "accountMember": {
      // ...
    }
  }]
}
```

Exception: Throw error if accountId doesn't equal to current account ID.

**Comment by nguyenthienthanh** [comment]
I think we should create an action like: `findOrgsByAccountId` with param is `accountId`.
To find all orgs of current user, we should use `findCurrentAccountOrgsQuery`, this query will call to `findOrgsByAccountId` action with `accountId` is `context.user.id`.

**Comment by duongdev** [comment]
So, `findCurrentAccountOrgsQuery` should be on `accounts` service or `orgs` service?

**Comment by duongdev** [comment]
I've done this issue
