### ISSUE TITLE
Should we highlight the member's username of the current signed-in user?

### ISSUE THREAD

**Issue by duongdev** [targeek/guru-erp#293]
Similar to Slack, should we highlight the username of the current signed-in member to let them get attention when they are mentioned? @QiuJey 

![image.png](https://images.zenhubusercontent.com/5ce4fea614421ce2b8548413/986adcd3-a71c-4da0-bb76-e5b249fc3434)
![image.png](https://images.zenhubusercontent.com/5ce4fea614421ce2b8548413/17a3ac54-5b82-4f20-a49f-de3545ff004b)
![image.png](https://images.zenhubusercontent.com/5ce4fea614421ce2b8548413/0dd24bc3-b3c7-4bd0-b6da-746bbb2609fa)

**Comment by QiuJey** [comment]
Sure, good way to separate pending, banned and active user  @duongdev 
<img width="694" alt="Screen Shot 2019-05-23 at 5 38 12 PM" src="https://user-images.githubusercontent.com/13997013/58246547-92e14200-7d81-11e9-97bc-102338f5dc2c.png">

**Comment by duongdev** [comment]
Banned members should be ~line-through~?

**Comment by duongdev** [comment]
Resolved by #328
