### ISSUE TITLE
Define colors constants to make them reusable

### ISSUE THREAD

**Issue by duongdev** [targeek/guru-erp#294]
![image](https://user-images.githubusercontent.com/9253690/58246470-56154b00-7d81-11e9-836d-cbe8146012ee.png)
![image](https://user-images.githubusercontent.com/9253690/58246472-5ad9ff00-7d81-11e9-97bb-71cadacc3d14.png)
![image](https://user-images.githubusercontent.com/9253690/58246491-64fbfd80-7d81-11e9-87cd-5a2ef4838721.png)

**Comment by duongdev** [comment]
Could we follow [Material Colors](https://material.io/tools/color/#!/?view.left=0&view.right=0) @QiuJey ?

**Comment by duongdev** [comment]
@QiuJey ping!

**Comment by QiuJey** [comment]
![image](https://user-images.githubusercontent.com/13997013/58308253-43575080-7e2b-11e9-85f7-c79870dff800.png)
Consider again color system on Figma @duongdev and review it please !

**Comment by duongdev** [comment]
nice @QiuJey. will check 👍

**Comment by duongdev** [comment]
Done
